name: CI

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment to determine which job to run'
        required: true
        default: 'run all' 

jobs:
  job-1:
    if: github.ref == 'refs/heads/main' && github.event.inputs.comment=='run job 1'||github.event.inputs.comment=='run all'
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Running Job 1"

  job-2:
    if: github.ref == 'refs/heads/main' && github.event.inputs.comment=='run job 2'||github.event.inputs.comment=='run all'
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Running Job 2"

  job-3:
    if: github.ref == 'refs/heads/main' && github.event.inputs.comment=='run job 3'||github.event.inputs.comment=='run all'
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Running Job 3"
